name: Sync forks

on: 
  push:
    branches: [main]

jobs:
  run:
    name: Create PRs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fork: 
          - project-a
          - project-b
    steps:
      - uses: actions/checkout@v3
      - uses: repo-sync/pull-request@v2
        with:
          pr_allow_empty: false
          destination_branch: "fork/${{ matrix.fork }}"