name: Sync forks

on: 
  push:
    branches: [main]

jobs:
  sync:
    name: Create PRs
    runs-on: ubuntu-latest
    env:
      REMOTE_REPO: franklinkim/git-subtree-poc-common
      REMOTE_BRANCH: fork/project-a
    steps:
      - uses: actions/checkout@v3
      - uses: gorillio/github-action-cherry-pick@master
        with:
          pr_branch: 'fork/x'
