name: Sync forks

on: 
  push:
    branches: [main]

jobs:
  sync:
    name: Create PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Sync Branches PR
        uses: monoku/sync-branches-pr@0.0.3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SOURCE_BRANCH: "main"
          TARGET_BRANCH_STARTS_WITH: "fork/"